spring:
 application:
  name: AmazonImitation
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/commerce
  username: root
  password: arun
  hikari:
   connection-timeout: 30000

jpa:
 hibernate:
  ddl-auto: update

git:
 url: ${GIT_URL}
 username: ${GIT_USERNAME}
 token: ${GIT_TOKEN}
